### ISSUE TITLE
Create Team Contract

### ISSUE THREAD

**Issue by Yurui-Feng** [UBC-MDS/twitter-persona#4]
The contract should outline how you are committed to work together so that you are accountable to one another.

**Comment by roanraina** [comment]
The team contract has been completed. I have it stored locally. It is not supposed to be added to the github repo. I have send a copy on slack which we can submit via canvas. @Yurui-Feng

**Comment by Yurui-Feng** [comment]
Team contract created it using google doc and submitted to canvas
