### ISSUE TITLE
Pick an idea for the project

### ISSUE THREAD

**Issue by Yurui-Feng** [UBC-MDS/twitter-persona#6]
Package name: twitterpersona
Assess whether a twitter user is positive or negative based on the user's recent tweets

**Comment by roanraina** [comment]
I think we should focus the scope further into evaluating the "character" of users to determine if they are "worth" engaging with (ie not trolls). There are many examples of packages that simply provide sentiment analysis.

**Comment by Yurui-Feng** [comment]
> I think we should focus the scope further into evaluating the "character" of users to determine if they are "worth" engaging with (ie not trolls). There are many examples of packages that simply provide sentiment analysis.

Sounds like a good idea. I am willing to work on the function [sentiment_analysis.py](https://github.com/UBC-MDS/twitter-persona/blob/main/src/twitterpersona/sentiment_analysis.py) and I will probably use NLTK to get the sentiment of the user.
